### ISSUE TITLE
Reset FPGA Buttons

### ISSUE THREAD

**Issue by galaxybomb23** [norandomtechie/ece270-simulator#22]
There should be a button that allows the user to toggle all the buttons off/on. It would act as a Reset for the state of all the buttons so they don't have to shift-click them all.

**Comment by eduxstad** [comment]
I don't really understand the nature of this request. Would it need to toggle the buttons or just turn them all off/on? If you turn them all on, it's going to reset the board anyway. I can't really think of a situation were you are going to be toggling all/most of the buttons at once. We probably want to keep the behavior of the simulator as close to the behavior of the board as possible.

**Comment by galaxybomb23** [comment]
The main idea is that as you are testing the board you may toggle (shift click) buttons into the down position. If you are running multiple tests/have to keep changing the toggled ones it would be nice to have a button that reset the buttons to the raised position (or just resets the board) instead of shift clicking them all again.

**Comment by eduxstad** [comment]
If you need to test your module with that many inputs, I think it would be a better idea to create another module to simplify the input, like an encoder :)
